name: debug-build-test
on:
  push:
    branches:
    - master
    - dev
  pull_request:
    branches: 
    - master
    - dev

jobs:
  job:
    name: ${{ matrix.os }}-${{ github.workflow }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: windows-latest
            triplet: x64-windows
          - os: ubuntu-latest
            triplet: x64-linux
    env:
      BUILD_TYPE: Debug

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      # Setup the build machine with the most recent versions of CMake and Ninja. Both are cached if not already: on subsequent runs both will be quickly restored from GitHub cache service.
      - uses: lukka/get-cmake@latest

      - name: Setup anew (or from cache) vcpkg (and does not build any package)
        uses: lukka/run-vcpkg@v11 # Always specify the specific _version_ of the
                                  # action you need, `v11` in this case to stay up
                                  # to date with fixes on the v11 branch.

      - uses: ilammy/msvc-dev-cmd@v1

      - name: Configure CMake
        run: |
          cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -B ${{github.workspace}}/build -G Ninja

      - name: Build
        run: |
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target all --

      - name: Test
        if: runner.os == 'Linux'
        run: |
          ${{github.workspace}}/build/bin/filemod_test
      
      - name: Test
        if: runner.os == 'Windows'
        run: |
          ${{github.workspace}}/build/bin/filemod_test