name: debug-build-test
on:
  push:
    branches:
    - master
    - dev
  pull_request:
    branches: 
    - master
    - dev

jobs:
  job:
    name: ${{ matrix.os }}-${{ github.workflow }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: windows-latest
            triplet: x64-windows
          - os: ubuntu-latest
            triplet: x64-linux
    env:
      BUILD_TYPE: Debug

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: ilammy/msvc-dev-cmd@v1

      - name: Setup a new (or from cache) vcpkg (and does not build any package)
        uses: lukka/run-vcpkg@v11 # Always specify the specific _version_ of the
                                  # action you need, `v11` in this case to stay up
                                  # to date with fixes on the v11 branch.

      - name: CMake preset workflow (config, build and test)
        run: |
          cmake --workflow release-test-wf

      - name: Print failed tests
        if: failure()
        run: ctest --preset release-test --rerun-failed --output-on-failure